engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
        javascript:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - app/**/*
  - lib/**/*
exclude_paths:
- app/assets/fonts/
- app/assets/images/
- bin/rails
- bin/rake
- db/
- files/
- public/
- tmp/
- vendor/
